---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltd-keeper-api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ltd-keeper-api
  template:
    metadata:
      labels:
        name: ltd-keeper-api
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command:
            [
              '/cloud_sql_proxy',
              '-dir=/cloudsql',
              '-credential_file=/secret/file.json',
              '-instances=$(CLOUD_SQL_INSTANCE)',
            ]
          env:
            - name: CLOUD_SQL_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: ltd-keeper
                  key: cloud-sql-instance
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
            - name: cloudsql-secret-volume
              mountPath: /secret/
            - name: cloudsql-ssl-certs
              mountPath: /etc/ssl/certs

        - name: app
          imagePullPolicy: 'Always'
          image: 'lsstsqre/ltd-keeper:latest'
          ports:
            - containerPort: 3031
              name: ltd-keeper-uwsgi
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          env:
            # References the ltd-keeper-redis service
            - name: REDIS_URL
              value: 'redis://keeper-redis:6379'
            # Environment variables from the keeper configmap
            - name: LTD_KEEPER_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: ltd-keeper
                  key: profile
            - name: LTD_KEEPER_URL_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: ltd-keeper
                  key: url-scheme
            - name: LTD_DASHER_URL
              valueFrom:
                configMapKeyRef:
                  name: ltd-keeper
                  key: dasher-url
            # Environment variables from the keeper secret
            - name: LTD_KEEPER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: secret-key
            - name: LTD_KEEPER_AWS_ID
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: aws-id
            - name: LTD_KEEPER_AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: aws-secret
            - name: LTD_KEEPER_FASTLY_ID
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: fastly-id
            - name: LTD_KEEPER_FASTLY_KEY
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: fastly-key
            - name: LTD_KEEPER_BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: default-user
            - name: LTD_KEEPER_BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: default-password
            - name: LTD_KEEPER_DB_URL
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: db-url

      volumes:
        - name: cloudsql-secret-volume
          secret:
            secretName: cloudsql
        - name: cloudsql-ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}

---
# Deployment of celery workers for keeper
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltd-keeper-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ltd-keeper-worker
  template:
    metadata:
      labels:
        name: ltd-keeper-worker
    spec:
      containers:
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.16
          command:
            [
              '/cloud_sql_proxy',
              '-dir=/cloudsql',
              '-credential_file=/secret/file.json',
              '-instances=$(CLOUD_SQL_INSTANCE)',
            ]
          env:
            - name: CLOUD_SQL_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: keeper
                  key: cloud-sql-instance
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
            - name: cloudsql-secret-volume
              mountPath: /secret/
            - name: cloudsql-ssl-certs
              mountPath: /etc/ssl/certs

        - name: app
          imagePullPolicy: 'Always'
          image: 'lsstsqre/ltd-keeper:latest'
          command: ['/bin/bash']
          args: ['-c', '/home/appuser/run-celery-worker.bash']
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
          env:
            # References the keeper-redis service
            - name: REDIS_URL
              value: 'redis://keeper-redis:6379'
            # Environment variables from the keeper configmap
            - name: LTD_KEEPER_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: ltd-keeper
                  key: profile
            - name: LTD_KEEPER_URL_SCHEME
              valueFrom:
                configMapKeyRef:
                  name: ltd-keeper
                  key: url-scheme
            - name: LTD_DASHER_URL
              valueFrom:
                configMapKeyRef:
                  name: ltd-keeper
                  key: dasher-url
            # Environment variables from the keeper secret
            - name: LTD_KEEPER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: secret-key
            - name: LTD_KEEPER_AWS_ID
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: aws-id
            - name: LTD_KEEPER_AWS_SECRET
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: aws-secret
            - name: LTD_KEEPER_FASTLY_ID
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: fastly-id
            - name: LTD_KEEPER_FASTLY_KEY
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: fastly-key
            - name: LTD_KEEPER_BOOTSTRAP_USER
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: default-user
            - name: LTD_KEEPER_BOOTSTRAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: default-password
            - name: LTD_KEEPER_DB_URL
              valueFrom:
                secretKeyRef:
                  name: ltd-keeper
                  key: db-url

      volumes:
        - name: cloudsql-secret-volume
          secret:
            secretName: cloudsql
        - name: cloudsql-ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir: {}
