apiVersion: v1
kind: Service
metadata:
  name: keeper
  labels:
    name: keeper
spec:
  ports:
    - name: keeper-http
      protocol: TCP
      port: 8080
      targetPort: keeper-uwsgi
  selector:
    name: keeper-api
