apiVersion: v1
kind: Service
metadata:
  name: ltd-keeper
  labels:
    name: ltd-keeper
spec:
  ports:
    - name: ltd-keeper-http
      protocol: TCP
      port: 8080
      targetPort: api
  selector:
    name: ltd-keeper-api
