apiVersion: v1
kind: ConfigMap
metadata:
  name: ltd-keeper
data:
  LTD_KEEPER_PROFILE: 'production'
  LTD_KEEPER_URL_SCHEME: 'https'
  LTD_KEEPER_BOOTSTRAP_USER: 'admin'
  LTD_KEEPER_DB_URL: ''
  REDIS_URL: ""
  LTD_KEEPER_ENABLE_V1: "1"
  LTD_KEEPER_ENABLE_V2: "1"
