apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keeper-cm.yaml
  - keeper-deployment.yaml
  - keeper-service.yaml

images:
  - name: 'lsstsqre/ltd-keeper:latest'
    newTag: u-jsickcodes-deploy-2-0
