# This Services provides a cluster endpoint for the redis pod.

apiVersion: v1
kind: Service
metadata:
  name: keeper-redis
  labels:
    name: keeper-redis
spec:
  type: ClusterIP
  ports:
    - name: keeper-redis
      protocol: TCP
      port: 6379
      targetPort: keeper-redis
  selector:
    name: keeper-redis
