version: "3"
services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'user'
      POSTGRES_DB: 'db'
      PGPORT: '3308'
    ports:
      - '3308:3308'
    expose:
      - '3308'
    volumes:
      - ./pgdb:/var/lib/postgresql/data
