name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.8

      - name: Install tox
        run: pip install tox

      - name: Cache tox environments
        id: cache-tox
        uses: actions/cache@v2.1.4
        with:
          path: .tox
          # requirements/*.txt, pyproject.toml, and .pre-commit-config.yaml
          # have versioning info that would impact the tox environment.
          key: tox-${{ hashFiles('requirements/*.txt') }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run tox
        env:
          LTD_KEEPER_TEST_AWS_ID: ${{ secrets.LTD_KEEPER_TEST_AWS_ID }}
          LTD_KEEPER_TEST_AWS_SECRET: ${{ secrets.LTD_KEEPER_TEST_AWS_SECRET }}
          LTD_KEEPER_TEST_BUCKET: ${{ secrets.LTD_KEEPER_TEST_BUCKET }}
        run: tox -e lint,typing,py,coverage-report  # run tox using Python in path

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2.1.3
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install tox ltd-conveyor

      - name: Cache tox environment for docs
        id: cache-tox
        uses: actions/cache@v2.1.4
        with:
          path: .tox
          # requirements/*.txt, pyproject.toml, and .pre-commit-config.yaml
          # have versioning info that would impact the tox environment.
          key: tox-docs-${{ hashFiles('requirements/*.txt') }}-${{ hashFiles('pyproject.toml') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run tox
        run: tox -e docs

      - name: Upload documentation
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --gh --dir docs/_build/html --product ltd-keeper

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Define the Docker tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF} | sed -E 's,refs/(heads|tags)/,,' | sed -E 's,/,-,g')

      - name: Print the tag
        id: print
        run: echo ${{steps.vars.outputs.tag}}

      - name: Log into Docker Hub
        if: ${{ github.event_name == 'push' }}
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull previous images
        run: |
          docker pull lsstsqre/ltd-keeper:deps-${{steps.vars.outputs.tag}} || true
          docker pull lsstsqre/ltd-keeper:${{steps.vars.outputs.tag}} || true

      - name: Build the dependencies Docker image
        run: |
          docker build --target dependencies-image \
            --cache-from=lsstsqre/ltd-keeper:deps-${{steps.vars.outputs.tag}} \
            --tag lsstsqre/ltd-keeper:deps-${{steps.vars.outputs.tag}} .

      - name: Build the runtime Docker image
        run: |
          docker build --target runtime-image \
            --cache-from=lsstsqre/ltd-keeper:${{steps.vars.outputs.tag}} \
            --tag lsstsqre/ltd-keeper:${{steps.vars.outputs.tag}} .

      - name: Push Docker images
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push lsstsqre/ltd-keeper:deps-${{steps.vars.outputs.tag}}
          docker push lsstsqre/ltd-keeper:${{steps.vars.outputs.tag}}
